[2025-09-06T07:26:24.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T07:26:24.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:26:19.121428+00:00 [queued]>
[2025-09-06T07:26:24.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:26:19.121428+00:00 [queued]>
[2025-09-06T07:26:24.319+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T07:26:24.323+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_csv_to_postgres> on 2025-09-06 07:26:19.121428+00:00
[2025-09-06T07:26:24.329+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=373) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T07:26:24.329+0000] {standard_task_runner.py:64} INFO - Started process 374 to run task
[2025-09-06T07:26:24.328+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'load_csv_to_postgres', 'manual__2025-09-06T07:26:19.121428+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmpk9igomdg']
[2025-09-06T07:26:24.330+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask load_csv_to_postgres
[2025-09-06T07:26:24.352+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:26:19.121428+00:00 [running]> on host b38462e6beca
[2025-09-06T07:26:24.390+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T07:26:19.121428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T07:26:19.121428+00:00'
[2025-09-06T07:26:24.390+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T07:26:24.391+0000] {postgres.py:189} INFO - Running copy expert: 
            COPY bronze.customers_raw(
                customerid, age, gender, tenure, monthlycharges,
                contracttype, internetservice, totalcharges, techsupport
            )
            FROM STDIN WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"');
        , filename: /opt/***/data/customer_churn_data.csv
[2025-09-06T07:26:24.393+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-06T07:26:24.393+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-06T07:26:24.396+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T07:26:24.396+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_customers_to_postgres.py", line 101, in load_csv_to_postgres
    pg.copy_expert(sql=copy_sql, filename=csv_path)   # <-- pass path string here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 195, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY customers_raw, line 2: "1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.4,Yes,Yes"

[2025-09-06T07:26:24.402+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=load_customers_to_postgres, task_id=load_csv_to_postgres, run_id=manual__2025-09-06T07:26:19.121428+00:00, execution_date=20250906T072619, start_date=20250906T072624, end_date=20250906T072624
[2025-09-06T07:26:24.406+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 27 for task load_csv_to_postgres (extra data after last expected column
CONTEXT:  COPY customers_raw, line 2: "1,49,Male,4,88.35,Month-to-Month,Fiber Optic,353.4,Yes,Yes"
; 374)
[2025-09-06T07:26:24.430+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T07:26:24.441+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T07:26:24.442+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
