[2025-09-06T15:03:45.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T15:03:45.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.wait_for_csv manual__2025-09-06T15:03:43.987132+00:00 [queued]>
[2025-09-06T15:03:45.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.wait_for_csv manual__2025-09-06T15:03:43.987132+00:00 [queued]>
[2025-09-06T15:03:45.711+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T15:03:45.716+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): wait_for_csv> on 2025-09-06 15:03:43.987132+00:00
[2025-09-06T15:03:45.722+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T15:03:45.721+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'wait_for_csv', 'manual__2025-09-06T15:03:43.987132+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmp1g9g82ns']
[2025-09-06T15:03:45.722+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask wait_for_csv
[2025-09-06T15:03:45.722+0000] {standard_task_runner.py:64} INFO - Started process 3280 to run task
[2025-09-06T15:03:45.752+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.wait_for_csv manual__2025-09-06T15:03:43.987132+00:00 [running]> on host dd8e0e853e24
[2025-09-06T15:03:45.797+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T15:03:43.987132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T15:03:43.987132+00:00'
[2025-09-06T15:03:45.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T15:03:45.798+0000] {baseoperator.py:400} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-09-06T15:03:45.800+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-06T15:03:45.801+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2025-09-06T15:03:45.801+0000] {filesystem.py:85} INFO - Poking for file /opt/***/data/customer_churn_data.csv
[2025-09-06T15:03:45.802+0000] {filesystem.py:89} INFO - Found File /opt/***/data/customer_churn_data.csv last modified: 20250906141149
[2025-09-06T15:03:45.802+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-09-06T15:03:45.803+0000] {filesystem.py:85} INFO - Poking for file /opt/***/data/customer_churn_data.csv
[2025-09-06T15:03:45.803+0000] {filesystem.py:89} INFO - Found File /opt/***/data/customer_churn_data.csv last modified: 20250906141149
[2025-09-06T15:03:45.803+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T15:03:45.808+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=load_customers_to_postgres, task_id=wait_for_csv, run_id=manual__2025-09-06T15:03:43.987132+00:00, execution_date=20250906T150343, start_date=20250906T150345, end_date=20250906T150345
[2025-09-06T15:03:45.822+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-06T15:03:45.838+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-06T15:03:45.839+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
