[2025-09-06T07:23:13.481+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T07:23:13.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:23:09.249817+00:00 [queued]>
[2025-09-06T07:23:13.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:23:09.249817+00:00 [queued]>
[2025-09-06T07:23:13.501+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T07:23:13.505+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_csv_to_postgres> on 2025-09-06 07:23:09.249817+00:00
[2025-09-06T07:23:13.511+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T07:23:13.510+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'load_csv_to_postgres', 'manual__2025-09-06T07:23:09.249817+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmp9dwv3gse']
[2025-09-06T07:23:13.511+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask load_csv_to_postgres
[2025-09-06T07:23:13.511+0000] {standard_task_runner.py:64} INFO - Started process 194 to run task
[2025-09-06T07:23:13.533+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.load_csv_to_postgres manual__2025-09-06T07:23:09.249817+00:00 [running]> on host b38462e6beca
[2025-09-06T07:23:13.568+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T07:23:09.249817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T07:23:09.249817+00:00'
[2025-09-06T07:23:13.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T07:23:13.569+0000] {postgres.py:189} INFO - Running copy expert: 
        COPY bronze.customers_raw(customerid, age, gender, tenure, monthlycharges, contracttype, internetservice, totalcharges, techsupport)
        FROM STDIN WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"');
        , filename: <_io.TextIOWrapper name='/opt/airflow/data/customer_churn_data.csv' mode='r' encoding='utf-8'>
[2025-09-06T07:23:13.569+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T07:23:13.569+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_customers_to_postgres.py", line 96, in load_csv_to_postgres
    pg.copy_expert(copy_sql, f)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 190, in copy_expert
    if not os.path.isfile(filename):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not TextIOWrapper
[2025-09-06T07:23:13.575+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=load_customers_to_postgres, task_id=load_csv_to_postgres, run_id=manual__2025-09-06T07:23:09.249817+00:00, execution_date=20250906T072309, start_date=20250906T072313, end_date=20250906T072313
[2025-09-06T07:23:13.580+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task load_csv_to_postgres (stat: path should be string, bytes, os.PathLike or integer, not TextIOWrapper; 194)
[2025-09-06T07:23:13.611+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T07:23:13.621+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T07:23:13.622+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
