[2025-09-06T08:33:10.159+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T08:33:10.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T08:33:09.255625+00:00 [queued]>
[2025-09-06T08:33:10.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T08:33:09.255625+00:00 [queued]>
[2025-09-06T08:33:10.196+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-06T08:33:10.203+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-06 08:33:09.255625+00:00
[2025-09-06T08:33:10.211+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2216) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T08:33:10.209+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_transformations', 'dbt_deps', 'manual__2025-09-06T08:33:09.255625+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dbt_transformations.py', '--cfg-path', '/tmp/tmp46urmkif']
[2025-09-06T08:33:10.211+0000] {standard_task_runner.py:64} INFO - Started process 2217 to run task
[2025-09-06T08:33:10.211+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask dbt_deps
[2025-09-06T08:33:10.241+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T08:33:09.255625+00:00 [running]> on host d3743a3a0ea9
[2025-09-06T08:33:10.288+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T08:33:09.255625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T08:33:09.255625+00:00'
[2025-09-06T08:33:10.288+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T08:33:10.300+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-06T08:33:10.300+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR=/opt/***/dbt/profiles dbt deps']
[2025-09-06T08:33:10.308+0000] {subprocess.py:86} INFO - Output:
[2025-09-06T08:33:10.312+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-09-06T08:33:10.312+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-06T08:33:10.313+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T08:33:10.319+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-06T08:33:10.322+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_transformations, task_id=dbt_deps, run_id=manual__2025-09-06T08:33:09.255625+00:00, execution_date=20250906T083309, start_date=20250906T083310, end_date=20250906T083310
[2025-09-06T08:33:10.328+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 127.; 2217)
[2025-09-06T08:33:10.354+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T08:33:10.366+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T08:33:10.368+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
