[2025-09-06T09:21:06.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T09:21:06.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T09:21:05.523429+00:00 [queued]>
[2025-09-06T09:21:06.633+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T09:21:05.523429+00:00 [queued]>
[2025-09-06T09:21:06.634+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-06T09:21:06.643+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-09-06 09:21:05.523429+00:00
[2025-09-06T09:21:06.650+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T09:21:06.651+0000] {standard_task_runner.py:64} INFO - Started process 205 to run task
[2025-09-06T09:21:06.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_transformations', 'dbt_deps', 'manual__2025-09-06T09:21:05.523429+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_transformations.py', '--cfg-path', '/tmp/tmplxfi1ri3']
[2025-09-06T09:21:06.652+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_deps
[2025-09-06T09:21:06.761+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_transformations.dbt_deps manual__2025-09-06T09:21:05.523429+00:00 [running]> on host 2cd4a0d9f61c
[2025-09-06T09:21:06.829+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T09:21:05.523429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T09:21:05.523429+00:00'
[2025-09-06T09:21:06.830+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T09:21:06.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-06T09:21:06.844+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR="/opt/***/dbt/profiles" python -m dbt deps']
[2025-09-06T09:21:06.851+0000] {subprocess.py:86} INFO - Output:
[2025-09-06T09:21:06.989+0000] {subprocess.py:93} INFO - /home/***/.local/bin/python: No module named dbt.__main__; 'dbt' is a package and cannot be directly executed
[2025-09-06T09:21:06.994+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-06T09:21:06.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T09:21:07.002+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-06T09:21:07.005+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_transformations, task_id=dbt_deps, run_id=manual__2025-09-06T09:21:05.523429+00:00, execution_date=20250906T092105, start_date=20250906T092106, end_date=20250906T092107
[2025-09-06T09:21:07.012+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 1.; 205)
[2025-09-06T09:21:07.027+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T09:21:07.042+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T09:21:07.044+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
